### ISSUE TITLE
Link to example data: ecoli_reads_1.fq ecoli_reads_2.fq

### ISSUE THREAD

**Issue by tseemann** [SaraEl-Metwally/LightAssembler#4]
Where can we get the `ecoli_reads_1.fq ecoli_reads_2.fq` files to replicate your examples?

Every time I try on my own `fastq.gz` data I get this message:

```
--- Parameters extrapolation.

--- h(0):m(0):s(8) elapsed time.
--- start with gap size g = 8
--- average read length = 137
--- average sequencing coverage = 131

--- Uniform kmers sampling.

--- h(0):m(0):s(0) elapsed time.
--- total number of kmers in BloomA = 0
--- BloomA false positive rate = 0
--- probability of an incorrect kmer appears in the sample : 0.151046

--- Trusted/untrusted kmers filtering.

--- h(0):m(0):s(0) elapsed time.
--- total number of kmers in BloomB = 0
--- BloomB false positive rate = 0
--- LightAssembler can not assemble your dataset !!!
--- maximum supported read length for this version = 1024
--- try different values for k [kmer size] & g [gap size] or different dataset
```

**Comment by SaraEl-Metwally** [comment]
You can replicate our examples by using GAGE benchmark data sets [http://gage.cbcb.umd.edu/data/index.html](url)

**Comment by SaraEl-Metwally** [comment]
We simulated ten different data sets from E. coli reference genome [https://www.ncbi.nlm.nih.gov/nuccore/NC_000913.2](url) using Mason v0.1.2 [https://packages.seqan.de/mason/](url). These data sets are varying in coverage (25x,35x,75x,140x,and 280x) and average error rate (1% and 3%).  

You can also replicate our results using real benchmark data sets from GAGE [http://gage.cbcb.umd.edu/data/index.html](url) and Assemblathon bird data set with accession [https://trace.ddbj.nig.ac.jp/DRASearch/experiment?acc=ERX218680](url)

The exact command lines used for the simulated and real data sets can be found in the supplementary file attached with LightAssembler paper [http://bioinformatics.oxfordjournals.org/content/early/2016/07/27/bioinformatics.btw470.abstract](url)

**Comment by SaraEl-Metwally** [comment]
- We simulated ten different data sets from [**E. coli reference genome** ](https://www.ncbi.nlm.nih.gov/nuccore/NC_000913.2) using  [**Mason** v0.1.2](https://packages.seqan.de/mason/), these data sets are varying in coverage (25x,35x,75x,140x,and 280x) and average error rate (1% and 3%).  
- You can also replicate our results using real benchmark data sets from [**GAGE**](http://gage.cbcb.umd.edu/data/index.html)  and [**Assemblathon**](https://trace.ddbj.nig.ac.jp/DRASearch/experiment?acc=ERX218680) bird data set.
- The exact command lines used for the simulated and real data sets can be found in the supplementary file attached with [**LightAssembler**](http://bioinformatics.oxfordjournals.org/content/early/2016/07/27/bioinformatics.btw470.abstract) paper.

**Comment by tseemann** [comment]
Can you put the exact command lines into a machine readable file and put it in this github repository?

That would make much more sense.

**Comment by SaraEl-Metwally** [comment]
Done!
You can find the exact command lines in [LightAssembler Supplementary](https://github.com/SaraEl-Metwally/LightAssembler/blob/master/Replicate-our-results/LightAssembler_Supplementary.pdf)
Thanks!
